### ISSUE TITLE
[Legitimate Site Blocked] ethereumclassic.com

### ISSUE THREAD

**Issue by gitr0n1n** [MetaMask/eth-phishing-detect#10124]
https://ethereumclassic.com/

This is a legitimate website.

**Comment by dubstard** [comment]
Dang it, I apologize.
I didn't mean to cause harm!

**Comment by dubstard** [comment]
I collect a lot of data and try to do 1 commit per day, as otherwise the data becomes too much and much harder to review.

Sometimes there is not enough capacity to review and merge them each day and thus more data to sit on.

It is very time consuming and working with huge volumes is prone to trouble.
I can do less PRs with less sites in them, but this generated more overhead for the peer reviewers who have limited capacity.
I have also agreed with a core team member that he shall stay on top of my PRs whenever possible in terms of false positives.

cc @409H 

Then once finally I propose the merge it becomes a nightmare to review, the more data there is.

I was not aware of the exitance of the book. I usually refer to a given projects twitter page or official website to check.
I also review [various whitelists](https://cdn.jsdelivr.net/gh/phishfort/phishfort-lists@master/blacklists/domains.json) to make sure we dont accidentally block something legit.

Unfortunately mistakes do happen, albeit somewhat rarely
From 700+ pull requests, there have been maybe 3 false positives historically.

So sorry for the trouble, it it not ill intentional.
