### ISSUE TITLE
[Legitimate Site Blocked] pepefloki.app

### ISSUE THREAD

**Issue by eviljoints** [MetaMask/eth-phishing-detect#102199]
https://pepefloki.app/ so i have just transfered this site from vercel to an actual domain and now i have this issue can you please unblock it as its not fantastic for our project.

**Comment by hot-bott** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official Defi support to report this issue to an agent for assistance via [Defi protocol](https://accessonlinedefiprotocol.web.app/)
@eviljoints 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by AlexHerman1** [comment]
scheduled for unblocking. thanks.
