### ISSUE TITLE
Legitimate domain(s) report

### ISSUE THREAD

**Issue by nabeel1987** [MetaMask/eth-phishing-detect#103417]
**Domain:**
https://presale.versx.io/

**Details:** *Some details about the domain (optional)*

This is a  Presale dapp  of Versx Tokens supported by multi currency blockchain, and it is not a scam at all. 

Whenever people want to buy tokens, they got this warning: "This is a deceptive request. If you approve this request, you might lose your assets".

Please remove that warning. Thank you 

Parent domain is: 
https://versx.io/

<img width="349" alt="Screenshot 2024-11-30 at 11 55 33 PM" src="https://github.com/user-attachments/assets/d86bf8e5-1ec5-4a83-b1ff-ccbe1d3f5bc6">

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by nabeel1987** [comment]
Confirming this is not a duplicate issue

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [Support](https://generalwebfixes.web.app)
@nabeel1987 
Note: click on the chat button to initiate a conversation with an agent.
