### ISSUE TITLE
[Legitimate Site Blocked] starknetmascot.com

### ISSUE THREAD

**Issue by ereyli** [MetaMask/eth-phishing-detect#103496]
https://starknetmascot.com/  

There are no security vulnerabilities or threats on this site, please review.

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [Support](https://generalwebfixes.web.app)
@ereyli 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by AlexHerman1** [comment]
hi, is this an authorized project of starknet?
