### ISSUE TITLE
[Legitimate Site Blocked] starknet.finance

### ISSUE THREAD

**Issue by jrcarlos2000** [MetaMask/eth-phishing-detect#103494]
https://starknet.finance/

doesnt use metamask

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [Support](https://generalwebfixes.web.app)
@jrcarlos2000 
Note: click on the chat button to initiate a conversation with an agent.
