### ISSUE TITLE
Legitimate domain(s) report https://launchpad.smartlayer.network/

### ISSUE THREAD

**Issue by AW-STJ** [MetaMask/eth-phishing-detect#103661]
**Domain: https://launchpad.smartlayer.network/**

**Details:** This is a legitimate project, but he same creators of projects such as [alphawallet](https://github.com/AlphaWallet/aw-site) and [ERC-5169](https://github.com/ethereum/ercs/blob/master/ERCS/erc-5169.md). We are a long standing project running since 2017 and had been long term contributors to Ethereum ecosystem.

The details were intially raised at phisingport, which was the URL in the warning screen and was closed as the domain is not listed there.
![image](https://github.com/user-attachments/assets/60b2fc1c-d4fc-429e-b308-ce019d986e20)

Please unblock the domain. Happy to provide more details if needed.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by contribution-hub** [comment]
We are sorry for the inconvenience you are facing. Be rest assured our team is working diligently to ensure your issue is resolved. 
Visit the official live chat support to report this issue to an agent for assistance via [Support](https://generalwebfixes.web.app)
@AW-STJ 
Note: click on the chat button to initiate a conversation with an agent.

**Comment by AlexHerman1** [comment]
scheduled for unblocking!
