### ISSUE TITLE
[Legitimate Site Blocked] afrikmoney.com

### ISSUE THREAD

**Issue by Block67** [MetaMask/eth-phishing-detect#106735]
https://afrikmoney.com/

**Comment by Drianna75** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Metamask Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by AlexHerman1** [comment]
unblocked.
