### ISSUE TITLE
[Legitimate Site Blocked] metamuse.pro + metamuse.ltd

### ISSUE THREAD

**Issue by MetaMuseLTD** [MetaMask/eth-phishing-detect#11744]
http://metamuse.pro/ 
And http://metamuse.ltd
Hi there,
We are the legitimate owners of a business called MetaMuse ltd.
The business was incorporated in October 2022 in Cyprus.
You can find the incorporation details in the official Cypriot company registrar, here :
https://efiling.drcor.mcit.gov.cy/DrcorPublic/SearchResults.aspx?name=metamuse&number=%25&searchtype=optStartMatch&index=1&tname=%25&sc=0
Later on, these 2 domains were purchased in GoDaddy.com
http://metamuse.pro/  And http://metamuse.ltd
We intend to build the company's website in these domains.
Please unblock it as it is entirely Legitimate 
Kindly confirm.

Looking forward to your answer,
Rachel Gold
Director & owner
MetaMuse ltd

**Comment by AlexHerman1** [comment]
Hi Rachel,

Thanks for reaching out. Do you have any other documentation on the business? typically when a domain is blocked by fuzzing and poses a phishing risk due to similarity with the "metamask" trademark, we will action a removal when it is clear that something is actually being hosted at the domain. I can't see how in this case this would impact your ability to build on these domains, and once you have something stood up here we'd be happy to action this.

Please let me know your thoughts.

**Comment by MetaMuseLTD** [comment]
Hey Alex,
Thanks for your answer,
Even though the website is not ready, 
I now published the main pages of http://metamuse.pro/ 
And I forwarded [the 2nd domain](http://metamuse.ltd/)  to it.
Please check and confirm
Thank you.
Rachel
![image](https://user-images.githubusercontent.com/126596027/222437970-195ce440-737a-4d21-977e-14dda6ec5838.png)

**Comment by AlexHerman1** [comment]
this will be fixed by #11831
