### ISSUE TITLE
[Legitimate Site Blocked] capitalvista.finance

### ISSUE THREAD

**Issue by SopeDapo** [MetaMask/eth-phishing-detect#14344]
https://capitalvista.finance/

**Comment by AlexHerman1** [comment]
hey @SopeDapo  can you provide some context on what this site is and whether it has an internet/social media presence?

**Comment by JanetteLicorne** [comment]
Hello, I am faced with a problem that my company’s website is among your scammers and transmits this information to the Opera browser, which is why when you open the site in Opera, information appears that the store is a scammer, indicating that the source of this information is MetaMask. 
Our website addres is w-stom.ru
![danger](https://github.com/MetaMask/eth-phishing-detect/assets/152372402/aa834130-0fd4-4bf1-993c-e29c76768f72)
![screen](https://github.com/MetaMask/eth-phishing-detect/assets/152372402/4a04438d-ab97-4dc2-a75b-5c6149a7a5aa)
