### ISSUE TITLE
https://bitballoon.com main site

### ISSUE THREAD

**Issue by Datapotomus** [MetaMask/eth-phishing-detect#1483]
Nothing wrong with the main site. The main site is run by netifly. Allows autmated deployments of static websites via zip uploads.

**Comment by 409H** [comment]
Hi, I've blacklisted the domain so that subdomains are autoblacklisted too. I did this as many many trust-trading scam sites are being hosted there, and this was a quick win to keep the community safe. Apologies for any inconvience with it.

See: https://github.com/MetaMask/eth-phishing-detect/issues/1081
