### ISSUE TITLE
Every site at .rf.gd domain is blocked

### ISSUE THREAD

**Issue by abstrakct** [MetaMask/eth-phishing-detect#1491]
It looks like every site ending with .rf.gd is blocked:

https://github.com/MetaMask/eth-phishing-detect/blob/4157b242f0b52fe84550145d55679bb2a88d3607/src/config.json#L320

.rf.gd is provided by infinityfree.net as a free domain, see the FAQ at infinityfree.net
Or if you open rf.gd in a browser without MetaMask it redirects to infinityfree.net

While I understand free hosting providers are probably used often for phishing sites, it seems a bit aggressive to completely block every site on that provider.
I have a simple little website myself with .rf.gd as the domain, that has nothing to do with ethereum or crypto in any way, and it still gets blocked, making it look suspicious if you try to access it in a browser with MetaMask installed.

**Comment by 409H** [comment]
Hi there,

You're right, it's an aggresive approach and I made the call to temporarily blacklist every subdomain on `rf.gd`.

Please give your domain so I can whitelist it on MetaMask. I'm working on a solution to be less aggresive, but protecting users is my primary concern as a list maintainer right now.

**Comment by abstrakct** [comment]
Ah, I see, and I absolutely agree that protection against phishing is extremely important. I own some crypto myself, and I use MetaMask, so I'm glad you have this protection! 

My domain is smbr.rf.gd and it's a php app that can make a randomized version of the good old Super Mario Bros. game. It hasn't been announced anywhere yet, so it's only me using it for now, but I would like to get some people to test it. I could of course tell them to turn off metamask before going to the site, but if you can whitelist it that would be even better. Thanks!

**Comment by daniyalakram** [comment]
http://bisbscs.rf.gd/

**Comment by coboMRDV** [comment]
http://allkleer-test.rf.gd/

**Comment by djmest** [comment]
mesfintenkirsblog.rf.gd please whitelist mine. Thank you!

**Comment by djmest** [comment]
[mesfintenkirsblog.rf.gd](url) please whitelist mine. Thank you!

**Comment by Percyjackson11** [comment]
Please whitelist my domain as well🙏🙏
Aviationport.rf.gd

**Comment by BlistHolme** [comment]
pieo.rf.gd
..it's Really Fxxn GooD!!!

0  =O)

**Comment by findselfimprovementbros** [comment]
Hello there,
I don't know if that issue has been fixed in any way, but I would like to leave this message for a requesting a whitelist.
I am running a website myself, ending on “rf.gd”. The URL is: https://find-self-improvement-bros.rf.gd 
Had I known about this problem with scammers using such endings I would have probably used another hosting service or completely different approach, but I am not too active within the crypto-world, so here we are.

Our website is currently a project for a self-improvement movement taking place on YouTube, inspired by the fairly known YTer “Hamza”. We currently have about 30 (active) Users using the website as a place to meet with new like-minded people, and expect more in the future. The concern is, that people who have a meta mask extension installed might not get access to this website (correct me if I'm wrong) therefore I would ask you to put us on a whitelist too. (SSL is installed on the website)

**Comment by vaminecHUN** [comment]
timelapse.rf.gd

**Comment by bren-uijl** [comment]
this is my domain
[mcedu.rf.gd](url)
please add it to the whitelist

**Comment by inLnx** [comment]
techboy234.rf.gd

**Comment by Bo-code** [comment]
Any chance you could whitelist my site please? [SafeConnect](https://safeconnect.rf.gd)

**Comment by mikecute123** [comment]
mine too please http://althea-flowers.rf.gd/
