### ISSUE TITLE
[Legitimate Site Blocked] www.metamash.io

### ISSUE THREAD

**Issue by Metmsh** [MetaMask/eth-phishing-detect#15010]
MetaMash is a legitimate website that through website information, blog posts and metaverse platform news reviews, aims to **compare metaverse platforms, offer information and upskill metaverse users** from around the world to get the best possible experience. MetaMash **does not intend to copy Metamask**, and does not, nor will not, be a platform for moving or keeping crypto currencies and tokens. 
https://www.metamash.io/

**Comment by AlexHerman1** [comment]
Hello,

This is blocked by our fuzzylist due to similarity to our domain. I don't think its prudent to bypass this given the fact that it is very similar and thus poses a significant phishing risk to our users if allowlisted. Please note that users will still be able to visit your site by clicking through.
