### ISSUE TITLE
[Legitimate Site Blocked] www.sleeplessai.net

### ISSUE THREAD

**Issue by ahmetkeyif** [MetaMask/eth-phishing-detect#15310]
https://www.sleeplessai.net/chat

**Comment by SleeplessAI-Lab** [comment]
This is Sleepless AI Lab. This webpage is a preview version of our previously developed AI chat page, and the activity has now been closed. 
In order to limit the pressure on our computing resources caused by excessive AI chatting, we have imposed some restrictions on chat behavior, and the user need to link a wallet before he/she can participate in the chat experience.
We hereby declare that during the process, we do not engage in any behavior that steals user privacy, wallet keys, or misuses user information.

**Comment by AlexHerman1** [comment]
this site is not even up.

**Comment by SleeplessAI-Lab** [comment]
You misunderstood. The chat section was part of our previous website activity, and the page is no longer open for user experience. We have our own pace for event planning, and there will be future check-ins.
