### ISSUE TITLE
Incorrectly flagged: EOSclassic.co

### ISSUE THREAD

**Issue by EOSclassic-EOSC** [MetaMask/eth-phishing-detect#1944]
We believe that this addition to the black list was made in bad faith by a competing project in an attempt to damage our momentum and reputation (our initial comments on the MyEtherWallet pull request here: https://github.com/MyEtherWallet/ethereum-lists/pull/717#issuecomment-399590294 )

We have always been up front about the motivations behind our project: we believe that there was significant value created by the EOS community through the EOS token crowdsale and subsequent distribution, and felt that creating a token that would honor everyone’s original EOS token balances with re-enabled trading would create value in the broader EOS community.

Our code has been reviewed by the MyCrypto.com development team, and was deemed clean (see the EOS Classic discussion about half way down): https://www.coindesk.com/eos-blockchain-isnt-live-yet-getting-closer/

Relevant quote: “The creators use something of a complicated process for users to claim their tokens, but MyCrypto CEO Taylor Monahan asked her team to look at it, and they don't see anything dangerous about an EOS holder claiming EOS Classic tokens.”

Our smart contract code is open source, both verified on EtherScan (https://etherscan.io/address/0xce3ad07c9c7a5f89d39eb1449913d3feecabcf8d#code)  and posted in Truffle-ready format on GitHub: https://github.com/EOSclassic-EOSC/EOSclassic

Further, we have received now over 3,100 organic claims through our marketing and outreach efforts, with significant momentum in particular from the Korean EOS community.  

To our claim that this pull request was done in bad faith, we provide a snapshot where the first mention of our domain was made in the EOS Classic Telegram: https://i.imgur.com/zPcC2Ym.png 

There have been several additional mentions of our ERC20 token project in their channel since our domain was shared in their Telegram channel on June 6th, 2018. It’s unfortunate that we share the same name, but when we launched there was no competition to speak of, so we ran with the EOSclassic name.

There is no reason why these two projects cannot co-exist, as our project, EOSclassic intends to stay as a token on the Ethereum blockchain, while EOS-Classic.io has forked Ethereum to create their own mineable blockchain.

We ask that this blacklist addition be reverted as soon as the maintainer can review our case, as anyone with Metamask installed cannot access our site. Thank you for your time.

**Comment by 409H** [comment]
Hi, I will review it. It was blacklisted because the CI was failing on PR 2949 (see CI: https://circleci.com/gh/MetaMask/eth-phishing-detect/2949?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

Your domain was added to `MyEtherWallet/ethereum-lists` repo in this PR https://github.com/MyEtherWallet/ethereum-lists/pull/717 with the following reason

> Scam: EOS Classic Impersonation (eos-classic.io)

I see now there has been an update to it. Give me a couple minutes to update myself

**Comment by EOSclassic-EOSC** [comment]
@409H appreciate the prompt response, thank you.

**Comment by 409H** [comment]
No problem. If you get pinged about MyEtherWallet reverting their blacklist, please ping me here and I'll action asap

**Comment by eosclassicteam** [comment]
eos-classic.io was the first project to use the symbol "EOS Classic" and the ticker "EOSC". In the case of "Bitcoin Classic" or "Bitcoin Clashic (Yes this is the fork of Bitcoin Cash) ", avoiding the use of same ticker or same coin name is a strict rule, in order to prevent name conflict on the services like CoinMarketCap or Coin exchanges. Also there is the case that exchanges and services changed the ticker of bitcoin cash from "BCC" to "BCH" in order to avoid conflict on trading coins. 

**Therefore using the same coin name on the different coin architecture or project must be avoided in a same manner.**

If @EOSclassic-EOSC you guys or team are planning to create a valid project for creating the token, please change your coin name or token to different symbol that avoids conflict with our team.

If the changes are not done by a reasonable time our team will report eosclassic.co or the following token https://etherscan.io/address/0xce3ad07c9c7a5f89d39eb1449913d3feecabcf8d as a illegal impersonation of EOS Classic [EOSC] coin which will be available on the next release of MyEtherWallet or MyCrypto.

**Requesting to not remove the commit in order to avoid conflict and since our "EOS Classic" team and the official project exists I think the warning message should not removed without enough consensus with us.**
