### ISSUE TITLE
Owner of site

### ISSUE THREAD

**Issue by GeoDk** [MetaMask/eth-phishing-detect#2057]
This is a new legit site, please give us time to get accepted

**Comment by 409H** [comment]
Which domain?

**Comment by GeoDk** [comment]
http://www.flycrypto.eu/

________________________________
Fra: H <notifications@github.com>
Sendt: Wednesday, July 11, 2018 4:51:47 PM
Til: MetaMask/eth-phishing-detect
Cc: GeoDk; Author
Emne: Re: [MetaMask/eth-phishing-detect] Owner of site (#2057)


Which domain?

**Comment by devenblake** [comment]
I'm closing this as stale for a couple reasons:
1) `mycrypto.com`, the fuzzylist entry that made `flycrypto.eu` get flagged, is as of #4644 not on the fuzzylist.
2) `flycrypto.eu` is no longer registered.
3) This issue is more than three years old.

Feel free to open a new issue if there's still a problem.
