### ISSUE TITLE
www.riden.network fraudulent phishing site

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/eth-phishing-detect#228]
www.riden.network has been identified as a malicious phishing site

**Comment by 409H** [comment]
Hi @jrmoreau are you saying it's incorrectly being identified as a malicious phishing site? 

If you are, it's because the site (was at the time of PR https://github.com/MetaMask/eth-phishing-detect/pull/226 6 hours ago) was pretending to be a Raiden crowdsale site.

https://urlscan.io/result/b8ee203e-8619-49d8-86c9-17ba3e2bf122#summary

![image](https://user-images.githubusercontent.com/2313704/31746036-3c613938-b45d-11e7-90a9-dfb6acc3e52d.png)

And a snippet from [the DOM](https://urlscan.io/result/b8ee203e-8619-49d8-86c9-17ba3e2bf122/dom/) (notice all the raiden.network references)

```
<base href="https://raiden.network">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">-->
  <meta name="description" content="The Raiden Network">
  <!-- Begin Jekyll SEO tag v2.3.0 -->
  <title>Raiden Network - Fast, cheap, scalable token transfers for Ethereum</title>
  <meta property="og:title" content="Raiden Network - Fast, cheap, scalable token transfers for Ethereum">
  <meta name="author" content="C.S.">
  <meta property="og:locale" content="en_US">
  <meta property="og:site_name" content="Raiden Network - Fast, cheap, scalable token transfers for Ethereum">
  <meta property="og:image" content="http://raiden.network/img/Raiden_logo.png">

  <script async="" src="https://www.google-analytics.com/analytics.js"></script>
```
