### ISSUE TITLE
wrong domain blacklisted

### ISSUE THREAD

**Issue by ether-man** [MetaMask/eth-phishing-detect#2337]
hi guys,
can you please whitelist etherman.app
the project is not yet live and already blocked from your plugin.
im not related with etherman.com or any other etherman projects.

the content of etherman.app will be a browsergame similar to bomberman.
you're welcome to try it out in about 2 weeks.

cheers

p.s. ssl certificate is also valid

**Comment by jeajam45** [comment]
Please help me get back to my online activity in empowr.com. It's been more than 2 days ago since I can't access my domain. I'm wondering why this has happened whereas I don't even know yet how to trade via my ethereum wallet. Please advise...
![welcome empowr screenshot](https://user-images.githubusercontent.com/38998443/49146337-e7f54b80-f33c-11e8-95a7-d7f6dec36120.png)
