### ISSUE TITLE
Twitter "Elon" bulk scam sites

### ISSUE THREAD

**Issue by nepeat** [MetaMask/eth-phishing-detect#2359]
Found on a text file of a scammer site.

```
medium-platform.com
medium-info.com
binance-claims.com
ethereum-corporation.com
airdrops-get.claims
airdrops-get.fund
airdrops-official.fund
airdrops.claims
airdrops.fund
binance-corporation.fund
binance-get.fund
binance-gift.fund
binance-official.fund
binance-presents.claims
binance-presents.fund
binance-take.claims
binance-take.fund
btc-official.fund
coinbase-corporation.claims
coinbase-corporation.fund
eth-official.claims
eth-official.fund
get-yours.fund
official-btc.claims
official-btc.fund
official-eth.fund
binance-get.claims
binance-gift.claims
elon-has-surprise.com
elon-has-surprise.org
elon-shares-present.com
musk-has-surprise.com
musk-has-surprise.org
safe-claims.info
safer-claims.info
claim-bonus.info
elon-secure.com
musk-share.info
secure-claim.info
secure-claims.info
elon-surprise.site
elon-get.site
official-claim.site
secured-connection.site
surprise-elon.site
ethereum-foundation.info 
ethereum-foundations.info
musk-pravduh.info
elon-pravduh.info
pravduh-elon.info
musk-official.com
musk-share.com
elon-giveaway.org
elon-surprise.org
tesla-elon.team
musk-surprise.org
elontesla.team
musk-surprise.info
musk-prize.info
bitztly.info```

**Comment by devenblake** [comment]
I ran through every domain in this list.
- medium-platform.com: unregistered
- medium-info.com: Registered 2021-12-19.
- binance-claims.com: unregistered
- ethereum-corporation.com: unregistered
- airdrops-get.claims: unregistered
- airdrops-get.fund: unregistered
- airdrops-official.fund: unregistered
- airdrops.claims: Registered 2021-06-11.
- airdrops.fund: unregistered
- binance-corporation.fund: unregistered
- binance-get.fund: unregistered
- binance-gift.fund: unregistered
- binance-official.fund: unregistered
- binance-presents.claims: unregistered
- binance-presents.fund: unregistered
- binance-take.claims: unregistered
- binance-take.fund: unregistered
- btc-official.fund: unregistered
- coinbase-corporation.claims: unregistered
- coinbase-corporation.fund: unregistered
- eth-official.claims: unregistered
- eth-official.fund: unregistered
- get-yours.fund: unregistered
- official-btc.claims: unregistered
- official-btc.fund: unregistered
- official-eth.fund: unregistered
- binance-get.claims: unregistered
- binance-gift.claims: unregistered
- elon-has-surprise.com: unregistered
- elon-has-surprise.org: unregistered
- elon-shares-present.com: unregistered
- musk-has-surprise.com: unregistered

It was at this point where I accidentally closed this tab and almost had a heart attack thinking I'd have lost the contents of this box. Thank you GitHub.

- musk-has-surprise.org: unregistered
- safe-claims.info: unregistered
- safer-claims.info: unregistered
- claim-bonus.info: unregistered
- elon-secure.com: unregistered
- musk-share.info: unregistered
- secure-claim.info: unregistered
- secure-claims.info: unregistered
- elon-surprise.site: unregistered
- elon-get.site: unregistered
- official-claim.site: unregistered
- secured-connection.site: unregistered
- surprise-elon.site: unregistered
- ethereum-foundation.info: unregistered
- ethereum-foundations.info: unregistered
- musk-pravduh.info: unregistered
- elon-pravduh.info: unregistered
- pravduh-elon.info: unregistered
- musk-official.com: Registered 2021-09-21, has content but is not related to cryptocurrency.
- musk-share.com: unregistered
- elon-giveaway.org: Registered 2021-02-20.
- elon-surprise.org: unregistered
- tesla-elon.team: unregistered
- musk-surprise.org: unregistered
- elontesla.team: unregistered

It was at this point that `whois.com` made me fill out a Google Captcha because of the volume of my queries.

- musk-surprise.info: unregistered
- musk-prize.info: Registered 2021-05-25.
- bitztly.info: unregistered

---

It looks like of those domains listed that are actually registered, all were registered after this issue was filed. Of those, only one had content, and I believe it's a Chinese hot tub website? Not related to cryptocurrency. So it doesn't seem like any site listed is related to cryptocurrency, though I've no doubt these were scams at some point.

I'm gonna close this issue. If you can't re-open it and have further related information, comment and I can do so myself. Thanks for contributing these regardless of if they were actionable or not - it's the thought that counts and if any of these were actionable it could have stopped someone getting scammed.
