### ISSUE TITLE
Litecoin One Project

### ISSUE THREAD

**Issue by Gulzaman786** [MetaMask/eth-phishing-detect#2376]
Hi , i'm Gulzaman Khan From Litecoin One , MetaMask believes That Litecoin One Website could currently compromise your security and has prevented you from interacting with it, But we  believes that our website  incorrectly flagged And blocked by MetaMask , Kindly review our site www.litecoinone.org and approve as soon as possible ,

Thank you

**Comment by 409H** [comment]
Hello.

The domain has been blacklisted because the team is fake - as described here: https://etherscamdb.info/domain/litecoinone.org - not to mention "Gulzaman Khan" is not even listed on the "team".

![image](https://user-images.githubusercontent.com/2313704/45396202-f7b09e00-b631-11e8-8ca8-3f39793f90c7.png)

**Comment by Gulzaman786** [comment]
Waiting for approval .....

**Comment by 409H** [comment]
> It is not necessary that only pictures must be real but It is important that the people behind the project should be good

A big red flag is an anonymous team when doing an ICO - even the names do not match (even if the pictures are stock images)
Please update your website.
