### ISSUE TITLE
Unblock http://4ever.fun

### ISSUE THREAD

**Issue by Paul955** [MetaMask/eth-phishing-detect#2424]
Please allow access to the site 4ever.fun The project is working. I'm an investor and I use the MetaMask application. Please remove the site 4ever.fun from the blacklist. I've been working with 4ever.fun since the beginning of its discovery.

**Comment by 409H** [comment]
Hi. I am the one who actioned the blacklist. Although I do not work for MetaMask, I am a contributor to these blacklists.

It is a ponzi scheme. If you haven't been scammed now there is no telling that you wouldn't be scammed in the future. Ponzi schemes are illegal and unethical. Anything with guaranteed daily returns/dividens is most likely a scam.

**Comment by xlab** [comment]
@409H The only unethical thing there is to block other people's work just because of an opinion of a single man, based on his life views. Without appeals or even strict guidelines what is forbidden and what is not.

The contract is a crypto game, the same as a crypto casino. You know that casinos exist and that a typical casino takes money from half of people and re-distributes it among the other half and 1% goes to the casino owners? Isn't that a scam thing and unethical, based on your views?

The contract works, there is the source published and it works straightforward, it's far more open than a typical crypto casino. People are interacting with it on their own will. I personally lost $400 on CryptoKitties, just because the kitties I invested in lost their value due to new feature announces from the game creators, so what now? I'm dealing with it, but believe me that was far more UNFAIR.

Please stop broadcasting your life views to the public by taking action on the other people's projects that are trying to make games using Ethereum. Alternatively, please provide guidelines for the project owners, so the could put **appropriate notices** on their website, to avoid confusion among the users.

@409H I hope you understand the situation better 👍

**Comment by ForbiMan** [comment]
Hello community. 
Please allow access to the  site 4ever.fun 
The project is working. 
I'm an ordinary investor, and I use the MetaMask application.
Please remove the 4ever.fun site from the blacklist.
Best regards.
