### ISSUE TITLE
Etherean.org is not a scam :)

### ISSUE THREAD

**Issue by lrettig** [MetaMask/eth-phishing-detect#2598]
Hello friends,

Somehow the domain "etherean.org" ended up on MM's blacklist. It's a parked domain, there's nothing on it (yet), and it was never used as part of a scam, I can attest to this fact. Could you please remove the domain from the blacklist? It will be put to productive use shortly.

Thanks!

Lane Rettig
Ethereum core developer ^_^

**Comment by danfinlay** [comment]
Hi Lane,

I see no instance of Etherean on our blacklist:
https://github.com/MetaMask/eth-phishing-detect/search?q=etherean&unscoped_q=etherean

It seems most likely to me that it got hit by our levenshtein distance whitelist, since it's very similar to some protected domains.

I've added it to our whitelist to bypass the levenshtein distance. Reopen if this doesn't fix the issue in ~15 minutes.
