### ISSUE TITLE
Please remove coindeskjapan.com from warning list 

### ISSUE THREAD

**Issue by togawa-z** [MetaMask/eth-phishing-detect#2828]
We have domain coindeskjapan.com.
We will start media service on March, 2019.

cf.
https://www.nikkei.com/article/DGXLRSP498321_X11C18A2000000/

So, please remove coindeskjapan.com from warning list.

**Comment by bunzoono** [comment]
Hi @409H ,
Please remove the flag on this(https://www.coindeskjapan.com/) domain.
Thanks,

**Comment by 409H** [comment]
Will page PhishFort regarding this.

**Comment by tehnlulz** [comment]
Thanks - We've removed on our side. Just FYI, @bunzoono @togawa-z we've seen a whole bunch of phishing campaigns targeting exchanges and crypto companies following the format:

`
companyname + country.com
`

For example:
`
"bithumbjapan.com",
"bithumbvietnam.com",
"vietnam-binance.com",
"binancevietnam.net",
"bithumbvietnam.info",
"vietnam-login-binance.com"
`
Which is why we immediately assumed it was phishing! Apologies!

**Comment by togawa-z** [comment]
@tehnlulz We got it. Thank you very much.
Do we just only have to wait for code merge?
