### ISSUE TITLE
https://decrypto.com.ar/

### ISSUE THREAD

**Issue by mochoa-espin** [MetaMask/eth-phishing-detect#3090]
Hello, 
Our develop team would like to ask to why is [decrypto.la](https://decrypto.la/) being blocked. 
The interactive page only gives us "This domain was blocked for its similarity to mycrypto.com, a historical phishing target."
In case of being a false positive, please add the site to the whitelist.

Best regards.

**Comment by gonzajavierperez** [comment]
Hello, from our development team we are in need, please, if you can review this issue. We need to interact with the apis of decrypto.com.ar and decrypto.la, and this is a problem for us. We will be waiting for an answer. Thank you very much.

**Comment by gonzajavierperez** [comment]
Hello, please we need to know how to proceed. Could you tell us? Thank you.

**Comment by gonzajavierperez** [comment]
Hi @409H, please could you tell me how to proceed? Thank you!

**Comment by gonzajavierperez** [comment]
Hi, according to this issue, we need to add decrypto.la and decrypto.com.ar to whitelist. We have opened a branch and asked for a pull request several times ( https://github.com/MetaMask/eth-phishing-detect/pull/3131 ), but it always seems to have merge conflicts because of new items in the whitelist. Please could you help us adding decrypto.com.ar and decrypto.la to whitelist ?
Thank you very much.
