### ISSUE TITLE
Tortoken.io Domain is incorrectly flagged 

### ISSUE THREAD

**Issue by tkitki** [MetaMask/eth-phishing-detect#3097]
Hi,
we are Tor (TOR) group from Estonia. Tor (TOR) is produced independently from the Tor® anonymity software in USA (see our website footer), which means you flagged our website as a fake website of Tor® anonymity software is wrong. 
Scan: https://urlscan.io/result/219f9735-b85d-45b7-a6ab-62aa6a00b941
Please, add tortoken.io to whitelist. Thanks!

Best,
Tor (TOR)
Anonymous cryptocurrency based on Tor browser. Safe, Open source, Community run and maintained.
https://tortoken.io

**Comment by 409H** [comment]
Hi Tortoken, please can you address these comments:

https://twitter.com/bcrypt/status/1134598286600368128
https://twitter.com/eric_mccorkle/status/1135621583614173184
https://twitter.com/abditum/status/1135619113269641216

**Comment by tortokenio** [comment]
Dear 409H,

Please read the twitter carefully, they are regarding some spelling mistake as impersonating, this is funny and irresponsible, because our website is designed by a freelance website designer, we are not good in English and have not found the mistakes. 
Besides we have already claimed since the first day our website is online that 'Tor (TOR) is produced independently from the Tor® anonymity software', which means they claimed that we are fake of Tor® anonymity software was wrong and smug, they have not even take close look of our website and made the judgement hastily. 
Also we have already made the declaration on our twitter and telegram: 'Tor (TOR) is a decentralized cryptocurrency based on Tor browser to provide a secure, fast and anonymous payment. Tor (TOR) is produced independently from the Tor® anonymity software (https://www.torproject.org) in USA. Tor (TOR) is NOT affiliated with Tor® anonymity software. Protecting privacy and freedom in cryptocurency is our goal to make Tor (TOR) project.' 
Twitter: https://twitter.com/tortoken/status/1135600967938973696
Telegram group: https://t.me/tortoken/11432
Telegram channel: https://t.me/tortokenchannel/16

Because of these false judgement, our early investors are losing money now, they are very nervous and sad. We think twitter should be a place to support freedom and privacy instead of spreading suspicion and hatred. So, please add tortoken.io to whitelist to stop this farce. Thanks!

Best,
Tor (TOR)
Anonymous cryptocurrency based on Tor browser. Safe, Open source, Community run and maintained.
https://tortoken.io

**Comment by pastly** [comment]
This account is purposefully toeing the line regarding legal use of the name "Tor" in order to boost their credibility.

They say they are based on Tor Browser, but haven't even bothered to fork Tor Browser publicly.

All the code they have forked (tor [not Tor Browser], stem, chutney, torspec) is just forked. [No public changes or modifications](https://github.com/tortokenio?tab=repositories).

When they were called out for [falsely claiming their CEO and COO used to be a Tor developers](https://twitter.com/bcrypt/status/1134598286600368128), they delete that claim from [their website](https://tortoken.io) instead of explaining how that mistake was made or how it is actually true (it isn't true).

The [whitepaper on their website](https://tortoken.io/whitepaper.pdf) allegedly for their *cryptocurrency* is just copy/paste from the [~15 year-old Tor *network* design paper](https://svn.torproject.org/svn/projects/design-paper/tor-design.pdf).

**I have no familiarity with this anti-phishing project of yours, but this domain 100% deserves to stay blacklisted. tortoken.io is trying to scam people.**

Shame on you @tortokenio. What you're doing is wrong, if not illegal too.
