### ISSUE TITLE
[Legitimate Site Blocked] app.trendx.tech

### ISSUE THREAD

**Issue by gpgcheck** [MetaMask/eth-phishing-detect#36536]
https://app.trendx.tech/, this site is legitimate, how to cancel the Warning?

**Comment by kdds2396** [comment]
Are you kidding me? This website stole thousands of dollars in cryptocurrencies from its users.

**Comment by trendxdevops** [comment]
Hello, we are the official operations team of Trendx (https://app.trendx.tech/). Today, we discovered that there is a website impersonating us and causing losses to users. We deeply regret this situation. Additionally, due to this issue (https://github.com/MetaMask/eth-phishing-detect/issues/36457) marking our website as a block domain, we would like to request the removal of our website from the blacklist. We have never provided any Polygon-related services.

**Comment by trendxdevops** [comment]
![WechatIMG176](https://github.com/MetaMask/eth-phishing-detect/assets/165745573/bb0e9aa2-75ae-4ab6-9917-adb0054ed3a0)

**Comment by trendxdevops** [comment]
> Are you kidding me? This website stole thousands of dollars in cryptocurrencies from its users.
> 
> Is trending on twitter!

  Hackers are using a phishing website (https://app-trendx.tech/airdrop) in Discord to deceive our users. Please block this domain。This website “app-trendx.tech” is a phishing，Not us, we are also victims.

**Comment by trendxdevops** [comment]
> @409H Can you help us with this?
> 
> > > Are you kidding me? This website stole thousands of dollars in cryptocurrencies from its users.
> > > Is trending on twitter!
> > 
> > 
> > Hackers are using a phishing website (https://app-trendx.tech/airdrop) in Discord to deceive our users. Please block this domain。This website “app-trendx.tech” is a phishing，Not us, we are also victims.

thanks!

**Comment by AlexHerman1** [comment]
done
