### ISSUE TITLE
report a bitcoinmix.org scam

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#3841]
.

**Comment by Itemlogic** [comment]
False positive. bitcoinmix.org definitely not a scam.

**Comment by coboguard** [comment]
Bitcointalk link proof: https://bitcointalk.org/index.php?topic=5240635.0

**Comment by Itemlogic** [comment]
So what does your bitcointalk thread prooves? You claiming project as a scam by showing non-sense screenshot with popups. How does this correlates with you scam/phishing statement? Looks like a jealous competitor who are trying to spoil the reputation of the project with no clear evidence. Good luck mate.

Also let us know why your github profile picture originates from https://www.penguinxmixer.io/concept page? Which is currently non accessible. Why https://www.penguinxmixer.io/ is quite similar to newly created mycryptomixer.com ?
Stop spreading fud. And do your own job.

**Comment by coboguard** [comment]
So why on reddit is another account you use multiple accounts at the same
time to say that you net not a scam ??. If I am a direct competitor why
would I be (
https://bitcointalk.org/index.php?topic=5245694.msg54358881#msg54358881)?
:). Are you like smartmixer this is not a scam today is yes it is a scam at
the exit. So bitcoinmix.org is the same it erases the traces soon the scam
to take it out I will destroy bitcoinmix big pub :) because you are a
service scammer

**Comment by Itemlogic** [comment]
**Do not mislead users with your fake reviews without any reason.**
Otherwise you can provide a Letter of Guarantee signed by bitcoinmix.org. I'm sure you don't have it and won't ever have.
By far the bitcoinmix.org is providing realiable service, much longer than other services.

I don't know why "would you do" or why are you doing these claims on reddit, github and bitcointalk. This type of question you could direct to yourself. If you truly believe such absurd type of marketing by spoiling competitor reputation will help you, be sure it won't. 

Also it is good that you mentioned smartmixer.io by yourself, because
https://penguinxmixer.io
https://smartmixer.io
https://mycryptomixer.com
https://coinomize.biz
are extremely similar, so better take a closer here.

Just leave bitcoinmix alone and try some other marketing options. It is a shame to use such dirty tricks. It won't lead you anywhere. Stop being jealous. GL mate.

**Comment by coboguard** [comment]
here your own launch to advertise the bitcoinmix service we see that you
are a scam because bitcointalk is the forum you mentioned as a scammer
https://bitcointalk.org/index.php?topic=2413192

**Comment by Itemlogic** [comment]
BitcoinMix.org doesn't have any official topic on bitcointalk.org. 
Warning on the top is related to a user that also has bunch of other strange threads which are not corresponding to the project itself.
Keep trying lol.

I do not see anything specific or real scam evidence in this topic. Another witch hunting on JS popups.

**Comment by BtcKing** [comment]
Coinomize is not a scam! I've used it many times. 
You are the same user who posted fake feedback on many pages for all Bitcoin mixers. 
Which mixer site do you own^^? You are just a Competitor.

**Comment by coboguard** [comment]
> Coinomize is not a scam! I've used it many times.
> You are the same user who posted fake feedback on many pages for all Bitcoin mixers.
> Which mixer site do you own^^? You are just a Competitor.

We haven't explained to you why are you here? it is not yours here that you do here? You are not mentioned in the discussion here in you have not spoken to you. Bye
