### ISSUE TITLE
Detection of walletgenerator.net

### ISSUE THREAD

**Issue by BlockGardener** [MetaMask/eth-phishing-detect#3978]
Hi Team,

I notice that the website http://walletgenerator.net/ is detected as malicious website.

The website allows you to create a public and private key pair for coins like Bitcoin and Litecoin.
At this time the website does not support Ethereum.

Could you elaborate why this website is detected as malicious website?

**Comment by 409H** [comment]
Because the website is compromised. We have written a detailed report here about how they are serving deterministic keypairs: https://medium.com/mycrypto/disclosure-key-generation-vulnerability-found-on-walletgenerator-net-potentially-malicious-3d8936485961

This logic keeps coming back: https://twitter.com/sniko_/status/1232317419835682817

**Comment by devenblake** [comment]
Closing due to age and lack of any continuing discussion here. Can be re-opened or re-filed if anyone has something important to add.
