### ISSUE TITLE
False positve on BluProducts.com

### ISSUE THREAD

**Issue by Technetium1** [MetaMask/eth-phishing-detect#5005]
`https://bluproducts.com`
Metamask says this site is on the block list. I don't think it should be.

**Comment by devenblake** [comment]
Explicitly blocked in #4747.

**Comment by devenblake** [comment]
This does look like it's the official Blu Products homepage. It was blocked because of the following two URL scans:

https://urlscan.io/result/90ddd4c1-8f62-4367-83af-d4ad08e467e5/

https://urlscan.io/result/0a9a5789-62cd-4c77-ab67-0f33721728b2/

Which look like scams that were hosted off the Blu Products website but are no longer on-line.

**Comment by davidwgrossman** [comment]
@409H thoughts?

**Comment by 409H** [comment]
`bluproducts.com` was put on the blocklist by me in commit https://github.com/MetaMask/eth-phishing-detect/pull/4747, which was made 2021-03-02. Whois data says the domain was lat updated 2020-02-05

Was the domain compromised?

**Comment by Technetium1** [comment]
This should be left blocked... In my opinion, they cannot be redeemed in any way after these actions:

https://www.ftc.gov/news-events/press-releases/2018/09/ftc-gives-final-approval-settlement-phone-maker-blu
https://threatpost.com/phone-maker-blu-settles-with-ftc-over-unauthorized-user-data-extraction/131679/
https://www.cnet.com/tech/mobile/these-cheap-phones-are-costing-you-your-privacy/
