### ISSUE TITLE
crypto.org is incorrectly flagged as phising site

### ISSUE THREAD

**Issue by calvinaco** [MetaMask/eth-phishing-detect#5096]
### Description

Recently some users and our developers reported that MetaMask is flagging https://crypto.org as phishing site. https://crypto.org is a legit-mate website which is the official website to the Crypto.org Chain, which is a public, open-source and permissionless blockchain.

![image](https://user-images.githubusercontent.com/38898718/120595788-85cdb200-c475-11eb-86ed-f9cfb9eae475.png)

Not every users are experiencing this issue, but it randomly appears from time to time and we would like to whitelist our domain so that it won't affect users browsing our website.

**Comment by Gudahtt** [comment]
Thanks for the report! But it looks like `crypto.org` is already on the whitelist. It does not appear to be blocked to me.

If your users encountered this page with MetaMask, then it's possible it was because MetaMask failed to update the phishing configuration due to network issues. Once the configuration updates successfully, this warning will no longer appear.

We will be updating our offline version of the config in the next release as well, so once that is deployed this should also be prevented.

**Comment by calvinaco** [comment]
Thanks @Gudahtt for the update.
