### ISSUE TITLE
MetaMask list our site as spam

### ISSUE THREAD

**Issue by AminoooV1989** [MetaMask/eth-phishing-detect#5244]
we had faced 2 times up to now 

that meta mask listed our site as a spam and we don't know why 

https://www.n7crypto.com/

**Comment by Gudahtt** [comment]
This domain does not appear to be blocked. Could you show where you saw this warning?

**Comment by AminoooV1989** [comment]
![Meta Mask Warning](https://user-images.githubusercontent.com/87974383/128178536-9d19a829-e941-49c1-9fb5-ac8f6e6c90ba.png)

**Comment by AminoooV1989** [comment]
the link if up may you check it please

**Comment by Gudahtt** [comment]
Sorry but that link is local to your computer. To check the version you need to open MetaMask, open the menu, click 'Settings', then scroll to the bottom of settings and click "About:

**Comment by AminoooV1989** [comment]
9.8.4

**Comment by Gudahtt** [comment]
It looks like the fallback phishing config used by MetaMask hasn't been updated in a while. I've just put up a PR to update it: https://github.com/MetaMask/metamask-extension/pull/11756

The config is supposed to update dynamically, but for you it is failing for some reason. Possibly due to something on your network, like a firewall.

I'm going to close this for now, since the fallback config will be updated by the linked PR. I'll bring up the failed dynamic update with the team as well, in case something is wrong there.
