### ISSUE TITLE
Looks like its still not right?

### ISSUE THREAD

**Issue by RossLegalSuite** [MetaMask/eth-phishing-detect#553]

**Comment by anbuvia** [comment]
This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

There are many reasons sites can appear on our warning list, and our warning list compiles from other widely used industry lists. Such reasons can include known fraud or security risks, such as domains that test positive on the Ethereum Phishing Detector. Domains on these warning lists may include outright malicious websites and legitimate websites that have been compromised by a malicious actor.

To read more about this site please review the domain on Etherscam.

Note that this warning list is compiled on a voluntary basis. This list may be inaccurate or incomplete. Just because a domain does not appear on this list is not an implicit guarantee of that domain's safety. As always, your transactions are your own responsibility. If you wish to interact with any domain on our warning list, you can do so by continuing at your own risk.

If you think this domain is incorrectly flagged or if a blocked legitimate website has resolved its security issues, please file an issue.

**Comment by 409H** [comment]
Please open a new issue @anbuvia
