### ISSUE TITLE
cloudpetstore.com is showing Phishing website

### ISSUE THREAD

**Issue by cloudpet** [MetaMask/eth-phishing-detect#610]
Our website cloudpetstore.com is banned by metamask, but we are an offical website with many real users. It is not a fishing website. Please remove our domain from the blacklist. Otherwise we will use legal means to recover our losses.

**Comment by 409H** [comment]
Hi @cloudpet - the domain `cloudpetstore.com` was blacklisted because it is a clone of popular game cryptokitties (1:1 feel and design, just a slight rebrand) and also links back to the official cryptokitties game in the footer.

> We are an official website

But you are redirecting users when logging-in to a separate domain: https://urlscan.io/result/7aacdbf0-aeac-49cf-8dbe-fbd59e5be845/dom/

There is also no confirmed affiliation between the original cryptokitties and you.

see: https://github.com/MetaMask/eth-phishing-detect/pull/609
