### ISSUE TITLE
[Legitimate Site Blocked] myetherwallet.crypto

### ISSUE THREAD

**Issue by ghost** [MetaMask/eth-phishing-detect#6309]
URL: `http://myetherwallet.crypto/`

This is definitely a false positive because this domain is listed on the featured sites of unstoppable domains

<img width="748" alt="Screenshot 2022-01-01 at 19 39 55" src="https://user-images.githubusercontent.com/81270448/147865525-ed4afcb5-0224-4cfe-93ba-ee9d54765e3c.png">

**Comment by D4v1dH03** [comment]
Sorry, used the interactive tool and checked why it is blocked.

**Comment by D4v1dH03** [comment]
Although its similarity, it is the new web3 version of the real domain `myetherwallet.com`

**Comment by devenblake** [comment]
Speaking as a person, I'm not officially affiliated with MetaMask anyway.

Unstoppable Domains looks like they're trying to be their own DNS provider and sell domains on TLDs that aren't [recognized by ICANN](https://data.iana.org/TLD/tlds-alpha-by-domain.txt). While they could potentially be validated by blockchain records it looks like this is going to be a huge and awful reckoning if ICANN ever opens up the TLDs on which Unstoppable Domains is unofficially squatting.

Because `myetherwallet.crypto` isn't actually a registered domain except through this one DNS provider (I could be wrong but I don't see anyone else providing .crypto registration or any other DNSes that can give an IP for a .crypto domain) I don't see much reason to treat this differently from a website that does not yet exist. If ICANN
