### ISSUE TITLE
[Legitimate Site Blocked] www.hugtus.com

### ISSUE THREAD

**Issue by Fatih3460** [MetaMask/eth-phishing-detect#6331]
https://www.hugtus.com/

Hi there, we just start new NFT project for developer community. Our website marked like phishing websites. How can we fixed?

**Comment by Fatih3460** [comment]
Hi Deven, thanks for the confirmation, but our website still appears to be scam. I hope there is a way to speed up or fix the process because it is affecting our business so badly. Thanks for your help in advance.

**Comment by devenblake** [comment]
I've submitted the PR I was drafting that included your site now rather than waiting until the end of the month. I have a feeling other people whose sites were also on that list were getting antsy as well, so no harm done. I can't give you an ETA on the fix but it's now moved forward a stage from where it was a couple minutes ago.

**Comment by Fatih3460** [comment]
Thanks a lot for your quick response. Have a great evening.
