### ISSUE TITLE
[Legitimate Site Blocked] openweb.science

### ISSUE THREAD

**Issue by vmandal** [MetaMask/eth-phishing-detect#6381]
https://openweb.science/

Although https://metamask.github.io/eth-phishing-detect/ say "This domain is not blocked! No problem here."

**Comment by devenblake** [comment]
The discrepancy between that tool and the filter in practice has already been noted in #5693; `openweb.science` is likely blocked because of its similarity to OpenSea (`openweb` and `opensea` both match `/open.e./`, though filtering is *not* done using regular expressions). This does seem to be falsely blocked.
