### ISSUE TITLE
[Legitimate Site Blocked] opensea.auction

### ISSUE THREAD

**Issue by citysenior** [MetaMask/eth-phishing-detect#6422]
https://opensea.auction/ 

_hi im citysenior  from uk london 
i apologise for not knowing much as i am currently learning .
and i would like to collaborate as i like to know what this means assuming you may be able to help ,_

below i copy and pasted this and have no idea what it means ,,
do you ?
can someone reach out and explain it 
thank you 
kind regards 
citysenior

 **Ethereum Phishing Detection**
****
This domain is currently on the MetaMask domain warning list. This means that based on information available to us, MetaMask believes this domain could currently compromise your security and, as an added safety feature, MetaMask has restricted access to the site. To override this, please read the rest of this warning for instructions on how to continue at your own risk.

There are many reasons sites can appear on our warning list, and our warning list compiles from other widely used industry lists. Such reasons can include known fraud or security risks, such as domains that test positive on the Ethereum Phishing Detector. Domains on these warning lists may include outright malicious websites and legitimate websites that have been compromised by a malicious actor.

**Comment by citysenior** [comment]
can we not find out who it is , just asking .

**Comment by devenblake** [comment]
A lot of people get scammed because they access websites with similar names to websites that they trust; **facebock.com** (notice the **bock** rather than **book**) isn't **facebook.com** but if the site name looks the same and the site itself looks the same, you might be tempted to give your password to a fake website run by a criminal. It's like building a fake grocery store next to a real grocery store and tricking people into buying fake food (and spending real money). This is called phishing. Here's an article that gives a better explanation: https://www.phishing.org/what-is-phishing

You were shown that message because **opensea.auction** strongly resembles **opensea.io** and the MetaMask extension noticed that this website could be a phishing scam.

If you mean to go to the real OpenSea, please use the URL **opensea.io**.

(This is *not* a duplicate of #6255).

**Comment by polstaaa** [comment]
how to fix this popping up???

**Comment by devenblake** [comment]
Please use **opensea.io**, *not* **opensea.auction**, to access OpenSea.

**Comment by polstaaa** [comment]
> Please use **opensea.io**, _not_ **opensea.auction**, to access OpenSea.

I tried opensea.io and this phishing detection is still popping up. How do I fix this???? Do I have to worry about this???

**Comment by devenblake** [comment]
As far as I know no users have reported false positives on opensea.io so most likely you're still accessing a phishing domain. Try this hyperlink:

https://opensea.io/

**Comment by polstaaa** [comment]
i clicked on this and i've been trying OPENSEA.IO and its still popping up.

**Comment by devenblake** [comment]
Is there any chance you could send a screenshot of the warning on opensea.io, with the address bar of the website visible?

**Comment by polstaaa** [comment]
No, but all the issues I've submitted came from OPENSEA.IO. and it's still happening. Every time I open Opensea, I get the phishing pop-up. And the pop-up never mentions any domain name.

**Comment by deshvin** [comment]
dupe #6255
