### ISSUE TITLE
[Legitimate Site Blocked] www.auctic.nl

### ISSUE THREAD

**Issue by Manomano22** [MetaMask/eth-phishing-detect#6527]
https://www.auctic.nl/

I don't know why, but this is my domain wich I bought a month ago. Just from shopify. And now when I visit my domain with a browser that has metamask on it it says Ethereum Phishing Detection. Can someone help me get this away? Nothing wrong with my website.

**Comment by Manomano22** [comment]
Can this be fixed or?

**Comment by Roestje** [comment]
I found your block reason on https://metamask.github.io/eth-phishing-detect/

"This domain was blocked for its similarity to auctus.org, a historical phishing target."
So because the name looks like auctus, they just blocked it upfront with no evidence that the website is really harmful.
We have the same issue with Ruckus.nl, a legitimate brand website. Let's hope for a quick solution.
