### ISSUE TITLE
[Legitimate Site Blocked] www.effinity.fr

### ISSUE THREAD

**Issue by AlexisDECOT** [MetaMask/eth-phishing-detect#6660]
https://www.effinity.fr/

Hi, I'm Alexis and I'm working for Effinity agency based in France. We have a little problem with your browser plugin because Effinity.Fr domain is blacklisted and a error message appears when we want to go on our website.

I speak about our website [https://www.effinity.fr/.] (https://www.effinity.fr/)
 and a error message appears when we go on.
The message says "To read more about this site please search for the domain on CryptoScamDB."
But when I Go on thehttps://cryptoscamdb.org/, i don't find anything about my website.
I don't understand why we are blacklisted.
If you want more details about us and how we do, it will be with pleasure. We are a marketing agency which works with large and medium business in France. We organise and launch marketing operations (affiliation & ads) but we don't have any links with your activity.

Thank you for your help !
Regards

Alexis DECOT
alexis.decot@effinity.fr

**Comment by AlexisDECOT** [comment]
Hello,

Anyone can do a reply to us please ?

Thank you,

**Comment by mcmire** [comment]
Hi @AlexisDECOT, we apply a similarity check to domains — if a domain is similar to another one that we've blocked then it will be blocked too. If you go [here](https://metamask.github.io/eth-phishing-detect/) and put in your domain name you can see that your domain is similar to `dfinity.org` and that's why it's being blocked. You can override this by submitting a PR that will add `effinity.fr` to the `whitelist` section in [`config.json`](https://github.com/MetaMask/eth-phishing-detect/blob/ba5ed06a95383f863a1553b95345b9bf40af7c3e/src/config.json). Cheers.

**Comment by AlexisDECOT** [comment]
Thank you for your reply.
How can we submit a PR ? (what is a PR ?)

Thank you,

**Comment by mcmire** [comment]
A PR is a pull request here on GitHub. It is a set of changes that we can pull in. If you are unfamiliar with this then it's probably best if we take care of this :) I've submitted a PR above and we can get that change pulled in once someone approves it.
