### ISSUE TITLE
[Legitimate Site Blocked] weatherscan.app, weatherscan.tk

### ISSUE THREAD

**Issue by haydenwalker980** [MetaMask/eth-phishing-detect#7281]
https://weatherscan.app/ is a weatherscan emulator lmao

So is https://weatherscan.tk/

**Comment by mrnamwen** [comment]
Seconding this. Weatherscan is not present on CryptoScamDB, nor does it interface with Metamask in any way. The entire project is open source (https://github.com/buffbears/Weatherscan/) so this can be confirmed if needs be. Why Blocked mentions that the block is due to its similarities to an Etherscan phishing site, despite the only similarity being "scan" in the domain.

**Comment by deshvin** [comment]
This domain does not resolve. Please feel free to re-open an issue when something is hosted on it.
