### ISSUE TITLE
[Legitimate Site Blocked] www.metabank.li

### ISSUE THREAD

**Issue by smokzee** [MetaMask/eth-phishing-detect#7368]
http://www.metabank.li/ please remove it from your list, this website will be a legitimate domain for a project which is based in the metaverse.

**Comment by VictorMetabank** [comment]
Hello, this is a new domain that we have acquired and we are trying to launch out business this week, and metamask as wrongfully included it in it's phishing list - without cause as it doesn't appear in any other lists including the https://cryptoscamdb.org/ that you reference - also being a new domain it is not linked to any fraud or scams.

Please remove it from your list, or at least give an indication of the steps we need to do in order to be removed from this list.

Since it's being a newly acquired domain it seems that it was just a misclassification based on the name or part of it.

Thanks,
Victor

**Comment by smokzee** [comment]
We would like to start our presale soon. Can you unblock our website please? On your "Why Blocked ?" page it it says:
"This domain was blocked for its similarity to metamask.io, a historical phishing target."

But we just recently acquired this domain.

**Comment by danfinlay** [comment]
This has been unblocked. It was automatically flagged for similarity to the metamask domain. https://github.com/MetaMask/eth-phishing-detect/pull/7513
