### ISSUE TITLE
Feature: generate minimal regex

### ISSUE THREAD

**Issue by kumavis** [MetaMask/eth-phishing-detect#7749]
https://stackoverflow.com/a/7433899

**Comment by BlockMageSec** [comment]
I know this is open for a long time now, but since I didn't see anything specific about testing this, I was curious to check it out and see what would happen. 

Taking the entire 'blacklist' array of strings from the current `src/config.json`, the results are pretty interesting. 

I have not figured out a good way to test this, however - so far I am pretty sure it's just timing out on compiling the REGEX.

Either way, cool idea.

**Script for reference:** [BlockMageSec/makeregex-js](https://gist.github.com/BlockMageSec/f3f8d710bedf901a5d7a38663fc7339f#file-makeregex-js)

**Output REGEX file:** [BlockMageSec/regexoutput-json](https://gist.github.com/BlockMageSec/f3f8d710bedf901a5d7a38663fc7339f#file-config-blacklist-regexoutput-json)

```
1.4M    ./config.json
620K    ./regex_output.txt
```

**Comment by samczsun** [comment]
Closing this out because it's become stale, and probably not a good use of engineering resources to re-architect the detector to support regex
