### ISSUE TITLE
[Legitimate Site Blocked] secure.transaction.openseal.art

### ISSUE THREAD

**Issue by TechnoPradyumnID** [MetaMask/eth-phishing-detect#8022]
https://secure.transaction.openseal.art/assets/0x6xe2f927b757642c0f160c82bbx9506c29cf1206x

**Comment by niosvargas** [comment]
https://secure.transaction.openseal.ws/assets/0x938f0500c9f0b48f5347c8334032205x3d63364ee

**Comment by foundersher12** [comment]
when i sell nft, one message me-





How do I sell NFTs using the Secure Transaction?

The OpenSea Secure transaction is the most secure type of buy/sell. With this type of transaction, the Buyer and Seller are guaranteed security in the form of additional verification to avoid fraud and illegal money laundering.

Selling NFT using OpenSea Secure transactions

The buyer must be verified before starting the transaction. After successful verification, OpenSea provides the buyer with a unique QR

This unique QR code must be sent by the buyer to the seller in person. The seller must scan the unique QR code with the camera of their device to access the OpenSea Secure transaction page. Once the wallet is connected, the seller must be successfully verified in order to receive the buyer's payment.

Note: One of the benefits of the OpenSea Secure transaction is the Personal Manager
If you have any questions, you can always contact the OpenSea Transaction Support Chat.
bozenakharitonova1's profile picture
Problem?




that is secure/ or hack? Which / please anybody kindly give solution

**Comment by VousataAgama** [comment]
It seems to be a fraud

**Comment by AVlCE** [comment]
Watch this video, turn on the subtitles, and everything will become very clear: https://www.youtube.com/watch?v=B0zzosuON7E
