### ISSUE TITLE
[Legitimate Site Blocked]: mydukaan.io

### ISSUE THREAD

**Issue by arjunbharti** [MetaMask/eth-phishing-detect#8774]
Hey, I checked the **bundle.js** in the browser and our domain (i.e [https://www.mydukaan.io](https://www.mydukaan.io)) is **neither in the whitelist, nor in the blacklist**.
I suspect some buggy code in the **detector.js** file. Meanwhile please whitelist our domain.

For your reference: [mydukaan.io](https://www.mydukaan.io) 
(and if you have some side-kicks, please do try us and build your online store in 30 seconds 😉)

**Comment by dubstard** [comment]
I don't find the domain explicitly blacklisted, not sure why this happens.
Perhaps one of the fuzzy checks mis-behaves.

Nota Bene: i am only a contributor, not a core team member and I can not merge nor whitelist.

**Comment by dubstard** [comment]
Edit:
```
Hi Apaac,
`hxxps://mydukaan[.]io/singlajiomart.is` impersonating and performing a phishing attack against [www.jiomart.com](http://www.jiomart.com/), an e-commerce platform launched on 2020 under the brand Jio Mart for online grocery shopping. We have reached you by official channels but had no response, so we put the site on our blacklist in the meantime. Please remove the infringing content before we can whitelist your site.

Thanks!
```

possibly this is why MM absorbed the blacklist entry from PhishFort (MetaMask partners with PF).

However the issue has been resolved by bot parties already.

If anybody can can create any website using your platform, whitelisting it means that if tomorrow on theory a rogue actor registers an account with you and attacks MetaMask - the attack will fly by undetected.

 
A lot of legitimate services get abused in this manner - Netlify, Web.App, Webflow.IO and so on.
We can no blanket white list them due to abuse.

**Comment by subhashchy** [comment]
I understand. And thank you for looking into it. 

However the difference between webflow or netlify and us is that we only do ecommerce shops of fixed designs. 
There is no way an e-commerce shop can impersonate meta mask in anyway. 

Like you saw we actively monitor and remove any troubling stores for general trademark violations.  

Even for trademark violation, as of now i am unable to find any open issue but still all stores are blocked. 

Since there are no open issues with any store on the platform right now, please remove the block. 

And in future if there is any issues reported, only that store should be effected (mydukaan.io/storename/* instead of entire domain.
