### ISSUE TITLE
[Legitimate Site Blocked] bnbminer.finance

### ISSUE THREAD

**Issue by TheRealDeveloper-BNBMiner** [MetaMask/eth-phishing-detect#8850]
https://bnbminer.finance/

Hello, @409H @AlexHerman1 @randymetamask and/or to whom it may concern:

I'm reaching out today because MetaMask is currently serving our users with a false warning about Phishing Detection. Our website/project has been operating on the Binance Smart Chain without issues for nearly two years and we currently have thousands of active users. We have also been in the top 10 Dapps list on the Binance Smart Chain by user volume for over an entire year. The invalid warning shown to our visitors is inflicting unwarranted damage on our public reputation. Our website does not ask users for sensitive information, nor does it require users to give any approvals or permissions.

Due to our popularity and success, scammers often attempt to pass themselves off as us using fake social media accounts and websites. We regularly warn our community about how to protect themselves from such attempts. Therefore, I assume this is simply a mix-up. Please help us correct this error ASAP.

Thank you in advance!

**Comment by CryptoGurl70** [comment]
You might want to show this to the group to let them know how to get past the warning. Some don't know how to get past it and think the site is just shut down but if they click on the last part of the message where it's underlined and says "continue at your own risk" that's the link that will take them to the site and allow them to use it instead of them thinking their only choice of to return to safety. Anyway here a visual that might help them. 
![orca-image-1612575776](https://user-images.githubusercontent.com/115894036/196006066-c9705c93-7ce1-44c3-84f1-b62a62f80f26.jpeg)

**Comment by TheRealDeveloper-BNBMiner** [comment]
@devenblake @ethphishingmaintainer1000

**Comment by onegoku** [comment]
I am using it for 1,5 years now and never got scammed. Also never saw them trying to get my wallet funds. All transactions have to be confirmed manually.
