### ISSUE TITLE
Crypto.pro -  it's not not phishing

### ISSUE THREAD

**Issue by iEuegene** [MetaMask/eth-phishing-detect#887]
[Сrypto.pro](https://crypto.pro/) - this is a forum, it's not not phishing. 
Good afternoon. Our users reported that Metamask marked the Forum as dangerous. They're surprised. We're surprised, too.
Please explain what the problem is?

**Comment by 409H** [comment]
Hi, most likely a false-positive since mycrypto.com was added to the fuzzy list.

I copy/pasted the link you gave, and that seems to be a IDN homograph attack of crypto.pro - https://urlscan.io/result/a6192ff0-48ed-4f50-acd8-9f542e1730cb
![image](https://user-images.githubusercontent.com/2313704/36259427-135401ea-1256-11e8-9f9a-70f1c159a259.png)

crypto.pro: https://urlscan.io/result/7c2c7947-4799-4a55-b4e9-35b467579ae9#summary

I shall whitelist the non IDN domain now.

**Comment by 409H** [comment]
Please allow ~15minutes for caches to update.
