### ISSUE TITLE
Legitimate domain(s) report: cuckoo.network

### ISSUE THREAD

**Issue by larkbirdy** [MetaMask/eth-phishing-detect#89066]
**Domain:** cuckoo.network

**Details:** *Some details about the domain (optional)* [cuckoo.network](https://cuckoo.network/) is Decentralized AI Creative Platform for Creators & Builders and it is not a  phishing site.

- [x] I have checked to make sure that [there is not a duplicate issue](https://github.com/MetaMask/eth-phishing-detect/issues)

**Comment by AlexHerman1** [comment]
please provide more information about this site. thanks.

**Comment by chidg** [comment]
Hi Metamask phishing team, 
Talisman users are complaining about Phishing warnings being raised for this url on our dapp. We believe it's because Talisman connects to the RPC `https://mainnet-rpc.cuckoo.network`. I can't make a claim either way for the safety of this domain, but a couple of things I note which suggest it's *probably* a false positive:
- It was added to this repo based on this issue which was a bulk report of many domains:  https://github.com/MetaMask/eth-phishing-detect/issues/88449
-  One subdomain of this domain was recently unblocked: https://github.com/MetaMask/eth-phishing-detect/issues/88938
- I personally connected a wallet containing funds to https://cuckoo.network/portal/staking in order to see what would happen. The site didn't ask me to sign anything or enter a seed phrase or anything else that demonstrated malicious intent.

It would be great to clear this up quickly either way so we can prevent our users seeing the warning.

**Comment by chidg** [comment]
Bump @AlexHerman1 - still getting reports from our users, would be great to have a decision on this soon.
