### ISSUE TITLE
[Legitimate Site Blocked] bakedbeans.io

### ISSUE THREAD

**Issue by kthnxbyee** [MetaMask/eth-phishing-detect#9062]
https://bakedbeans.io/

As one of the users and community members of this platform, I can undoubtedly confirm that this is a false flagging of a legitimate site that has no issues regarding user safety or any issues regarding problems with their users, and the Phishing warning the community is being given when visiting the link seems to have arisen with no foundation or functional purpose in this situation.

This DAPP has been live since November 6th, 2021, and is immutable meaning it cannot be altered in any way to harm its users.
It also appears that it is not marked as a scam site through your affiliate website CryptoScamDB and is also not listed as a blocked site through your interactive page accessible through your GitHub repo located at https://github.com/metamask/eth-phishing-detect

We as the staff and community kindly hope to hear from you regarding this DAPP and platform mistakenly being marked as a "threat site" by you as a company.

Thank you,
Kthnxbyee

**Comment by cryptokinggemz** [comment]
As a user, I agree that bakedbeans.io is completely safe. Pls Remove the warning.

https://bakedbeans.io/

As one of the users and community members of this platform, I can undoubtedly confirm that this is a false flagging of a legitimate site that has no issues regarding user safety or any issues regarding problems with their users, and the Phishing warning the community is being given when visiting the link seems to have arisen with no foundation or functional purpose in this situation.

This DAPP has been live since November 6th, 2021, and is immutable meaning it cannot be altered in any way to harm its users.
It also appears that it is not marked as a scam site through your affiliate website CryptoScamDB and is also not listed as a blocked site through your interactive page accessible through your GitHub repo located at https://github.com/metamask/eth-phishing-detect

We as the staff and community kindly hope to hear from you regarding this DAPP and platform mistakenly being marked as a "threat site" by you as a company.

Thank you,
Cryptoking Gemz

**Comment by madametalula** [comment]
As one of the users and community members of this platform, I can undoubtedly confirm that this is a false flagging of a legitimate site that has no issues regarding user safety or any issues regarding problems with their users, and the Phishing warning the community is being given when visiting the link seems to have arisen with no foundation or functional purpose in this situation.

This DAPP has been live since November 6th, 2021, and is immutable meaning it cannot be altered in any way to harm its users.
It also appears that it is not marked as a scam site through your affiliate website CryptoScamDB and is also not listed as a blocked site through your interactive page accessible through your GitHub repo located at https://github.com/metamask/eth-phishing-detect

We as the staff and community kindly hope to hear from you regarding this DAPP and platform mistakenly being marked as a "threat site" by you as a company.

Our original post regarding this issue is located here: 
https://github.com/MetaMask/eth-phishing-detect/issues/9062

Thank you,
Madametalula

**Comment by AlexHerman1** [comment]
this site is not live
