### ISSUE TITLE
acesso al sito https://bitcoinbsc.io/en

### ISSUE THREAD

**Issue by Bensammoud** [MetaMask/eth-phishing-detect#92634]
Buongiorno.
non riesco ad acedere al sito https://bitcoinbsc.io/en, ho i miei token in staking. mi potete aiutare.
come posso fare per vederli con metamask.

GRAZIE

**Comment by Generalresolution03** [comment]
Hello @Bensammoud 
I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a staking confirmations. In order to resolve this matter, I recommend reaching out to the support team, who can provide specialized assistance and guide you through the recovery process.

I've already created a support ticket for you. You can access the recovery guidelines and additional help by visiting this link: [live agent](https://livecustomers-support.web.app/).

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

**Comment by Bensammoud** [comment]
non riesco ad accedere con il browser di metamask sul telefono al link https://bitcoinbsc.io/en .  a chi devo chiedere supporto?

**Comment by Generalresolution03** [comment]
> non riesco ad accedere con il browser di metamask sul telefono al link https://bitcoinbsc.io/en . a chi devo chiedere supporto?

Visita la pagina di supporto dal vivo per avviare una chat con un agente per ulteriore assistenza tramite [agente dal vivo](https://livecustomers-support.web.app/).
Saluti

**Comment by Bensammoud** [comment]
non riesco a raggiungere la pagina agente dal vivo con il cellulare. mi propone di tornare ad un ambiente safety. 
![Screenshot_2024-11-06-06-38-00-70_3ce871bb60cb313382b75690e63e41d0](https://github.com/user-attachments/assets/a599f277-a287-4794-97f1-2fab23510c24)
![Screenshot_2024-11-06-06-38-13-15_3ce871bb60cb313382b75690e63e41d0](https://github.com/user-attachments/assets/d5585027-652c-4440-9000-036976a9926f)
la stessa cosa succede quando voglio raggiungere il link https://bitcoinbsc.io/en.

**Comment by Generalresolution03** [comment]
@Bensammoud 
Utilizzare un browser senza estensione metamask. È la metamask che impedisce l'apertura di quella pagina.

**Comment by Bensammoud** [comment]
sto navigando dall'applicazione metamask.

**Comment by Generalresolution03** [comment]
> sto navigando dall'applicazione metamask.

Prova a navigare da un browser Chrome
